// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delay.proto

#ifndef PROTOBUF_INCLUDED_delay_2eproto
#define PROTOBUF_INCLUDED_delay_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_delay_2eproto 

namespace protobuf_delay_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_delay_2eproto
namespace delayMessage {
class DelayMsg;
class DelayMsgDefaultTypeInternal;
extern DelayMsgDefaultTypeInternal _DelayMsg_default_instance_;
}  // namespace delayMessage
namespace google {
namespace protobuf {
template<> ::delayMessage::DelayMsg* Arena::CreateMaybeMessage<::delayMessage::DelayMsg>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace delayMessage {

// ===================================================================

class DelayMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:delayMessage.DelayMsg) */ {
 public:
  DelayMsg();
  virtual ~DelayMsg();

  DelayMsg(const DelayMsg& from);

  inline DelayMsg& operator=(const DelayMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DelayMsg(DelayMsg&& from) noexcept
    : DelayMsg() {
    *this = ::std::move(from);
  }

  inline DelayMsg& operator=(DelayMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DelayMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DelayMsg* internal_default_instance() {
    return reinterpret_cast<const DelayMsg*>(
               &_DelayMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DelayMsg* other);
  friend void swap(DelayMsg& a, DelayMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DelayMsg* New() const final {
    return CreateMaybeMessage<DelayMsg>(NULL);
  }

  DelayMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DelayMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DelayMsg& from);
  void MergeFrom(const DelayMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DelayMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double send_time = 2;
  void clear_send_time();
  static const int kSendTimeFieldNumber = 2;
  double send_time() const;
  void set_send_time(double value);

  // uint32 msg_id = 1;
  void clear_msg_id();
  static const int kMsgIdFieldNumber = 1;
  ::google::protobuf::uint32 msg_id() const;
  void set_msg_id(::google::protobuf::uint32 value);

  // uint32 uav_id = 3;
  void clear_uav_id();
  static const int kUavIdFieldNumber = 3;
  ::google::protobuf::uint32 uav_id() const;
  void set_uav_id(::google::protobuf::uint32 value);

  // double lat = 4;
  void clear_lat();
  static const int kLatFieldNumber = 4;
  double lat() const;
  void set_lat(double value);

  // double lon = 5;
  void clear_lon();
  static const int kLonFieldNumber = 5;
  double lon() const;
  void set_lon(double value);

  // double alt = 6;
  void clear_alt();
  static const int kAltFieldNumber = 6;
  double alt() const;
  void set_alt(double value);

  // double vx = 7;
  void clear_vx();
  static const int kVxFieldNumber = 7;
  double vx() const;
  void set_vx(double value);

  // double vy = 8;
  void clear_vy();
  static const int kVyFieldNumber = 8;
  double vy() const;
  void set_vy(double value);

  // double vz = 9;
  void clear_vz();
  static const int kVzFieldNumber = 9;
  double vz() const;
  void set_vz(double value);

  // @@protoc_insertion_point(class_scope:delayMessage.DelayMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double send_time_;
  ::google::protobuf::uint32 msg_id_;
  ::google::protobuf::uint32 uav_id_;
  double lat_;
  double lon_;
  double alt_;
  double vx_;
  double vy_;
  double vz_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_delay_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DelayMsg

// uint32 msg_id = 1;
inline void DelayMsg::clear_msg_id() {
  msg_id_ = 0u;
}
inline ::google::protobuf::uint32 DelayMsg::msg_id() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.msg_id)
  return msg_id_;
}
inline void DelayMsg::set_msg_id(::google::protobuf::uint32 value) {
  
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.msg_id)
}

// double send_time = 2;
inline void DelayMsg::clear_send_time() {
  send_time_ = 0;
}
inline double DelayMsg::send_time() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.send_time)
  return send_time_;
}
inline void DelayMsg::set_send_time(double value) {
  
  send_time_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.send_time)
}

// uint32 uav_id = 3;
inline void DelayMsg::clear_uav_id() {
  uav_id_ = 0u;
}
inline ::google::protobuf::uint32 DelayMsg::uav_id() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.uav_id)
  return uav_id_;
}
inline void DelayMsg::set_uav_id(::google::protobuf::uint32 value) {
  
  uav_id_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.uav_id)
}

// double lat = 4;
inline void DelayMsg::clear_lat() {
  lat_ = 0;
}
inline double DelayMsg::lat() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.lat)
  return lat_;
}
inline void DelayMsg::set_lat(double value) {
  
  lat_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.lat)
}

// double lon = 5;
inline void DelayMsg::clear_lon() {
  lon_ = 0;
}
inline double DelayMsg::lon() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.lon)
  return lon_;
}
inline void DelayMsg::set_lon(double value) {
  
  lon_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.lon)
}

// double alt = 6;
inline void DelayMsg::clear_alt() {
  alt_ = 0;
}
inline double DelayMsg::alt() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.alt)
  return alt_;
}
inline void DelayMsg::set_alt(double value) {
  
  alt_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.alt)
}

// double vx = 7;
inline void DelayMsg::clear_vx() {
  vx_ = 0;
}
inline double DelayMsg::vx() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.vx)
  return vx_;
}
inline void DelayMsg::set_vx(double value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.vx)
}

// double vy = 8;
inline void DelayMsg::clear_vy() {
  vy_ = 0;
}
inline double DelayMsg::vy() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.vy)
  return vy_;
}
inline void DelayMsg::set_vy(double value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.vy)
}

// double vz = 9;
inline void DelayMsg::clear_vz() {
  vz_ = 0;
}
inline double DelayMsg::vz() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.vz)
  return vz_;
}
inline void DelayMsg::set_vz(double value) {
  
  vz_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.vz)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace delayMessage

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_delay_2eproto
